-- -----------------------------
-- https://github.com/BRabbitFan
-- -----------------------------
-- Author       : BRabbitFan
-- Date         : 2021-03-12 21:19:02
-- LastEditer   : BRabbitFan
-- LastEditTime : 2021-03-12 21:19:44
-- FilePath     : /BigServer/Service/Hall/Main.lua
-- Description  : 游戏大厅--服务入口
-- -----------------------------

